###t Heading 3 for markdown test
> blockcode
**i'm a bold text**
*I'm an italic*
1. this is to test markdown code
2. This is a ordered list 
- This is an unordered list
- unordered list continued

`print (1)`

------------------------ Horizonal Rule ------------

[click me](https://localhost:8888/)

In [3]:
print (1)
while True:
    response = input("do you want to continue? (yes/no):")
    if response.lower() == 'no':    
        print("Exiting the loop.")
        break

1
Exiting the loop.


In [5]:
import numpy as np  
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
%timeit my_arr2 = my_arr * 2

%timeit my_arr2 = [x * 2 for x in my_list]


904 μs ± 21.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
90.9 ms ± 7.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
data = np.array([1.5, -0.1,3])
data
data * 10
data * data
data.shape
data.dtype




dtype('float64')

In [28]:
d1 = [6,7.5,8,0,1]

a1 = np.array(d1)

a1


array([6. , 7.5, 8. , 0. , 1. ])

In [33]:
d2 = [[1,2,3,4],[5,6,7,8]]
a2 = np.array(d2)
a2.dtype


dtype('int64')

(2, 4)

In [35]:
a2.ndim



2

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])