In [1]:
import numpy as np

a1 = np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [2]:
a2 = np.ones(3)
a2

array([1., 1., 1.])

In [3]:
a1 = np.array([1, 2, 3], dtype=np.float64)
a1
a1.dtype



dtype('float64')

In [4]:
a2=np.array([1, 2, 3], dtype=np.int32)
a2.dtype
a2.astype(int)


array([1, 2, 3])

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [6]:
float_arr=arr.astype(np.float64)
float_arr
#float_arr.dtype


array([1., 2., 3., 4., 5.])

In [7]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = arr.astype(np.int32)
int_arr

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [8]:
n_string = np.array(['1.25','-9.6','42'], dtype=np.string_)
n_string


array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [9]:
n_string.astype(np.float64)


array([ 1.25, -9.6 , 42.  ])

In [10]:
n_string.astype(float)


array([ 1.25, -9.6 , 42.  ])

In [11]:
a1 = np.array([[1,2,3,4], [2,2,3,4],[3,2,3,4]],dtype=np.float64)
a1

array([[1., 2., 3., 4.],
       [2., 2., 3., 4.],
       [3., 2., 3., 4.]])

In [12]:
a1.astype(np.float32)   
a1

array([[1., 2., 3., 4.],
       [2., 2., 3., 4.],
       [3., 2., 3., 4.]])

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
arr + arr
arr * arr
arr - arr



array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
arr + np.array([1,1,1])


array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
arr1 = np.array([1,2,3,4])
arr1 + 4  #broadcasting [4,4,4,4]




array([5, 6, 7, 8])

In [16]:
arr1 ** 2

array([ 1,  4,  9, 16])

In [17]:
1/arr1

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [18]:
arr2 = np.array([[0.,4,1],[7.,2,12]])
arr2


array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [19]:
arr2<arr


array([[ True, False,  True],
       [False,  True, False]])

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[5]

5

In [22]:
arr[5:8]

array([5, 6, 7])

In [23]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [24]:
arr_slice = arr[5:8]
arr_slice
arr_slice[1]=10
arr


array([ 0,  1,  2,  3,  4, 12, 10, 12,  8,  9])

In [25]:
arr[:]=64
arr

arr =np.arange(10)
arr

arr[5:8]  = 12

arr_slice=arr[5:8]
arr_slice [1] = 10
arr
arr_slice[:]=64
arr


array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [26]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[1]
arr_2d[1,2]
arr_2d[2,2]
arr_2d[:2]
arr_2d[:2,1:]
arr_2d[1,:2]
arr_2d[:,:1]
arr_2d[:,:1].shape
arr_2d[:1]
arr_2d[:1,:]
arr_2d[0,:]
arr_2d[:1,:].shape

(1, 3)

In [27]:

arr_1d = np.arange(1,10)
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr_1d = np.arange(1,10)

arr_2d = np.array([arr_1d[:3],arr_1d[3:6],arr_1d[6:]])
#arr_2d
arr_tmp = arr_2d[1,1:]

arr_tmp = arr_tmp - (arr_tmp+1)
#arr_tmp
arr_2d [1,1:] = arr_tmp

#arr_2d

new_row = np.array([['---','---','---']])
#new_row

                   
arr_2d = np.append(arr_2d,new_row,axis=0)
#arr_2d
arr_slice1 = arr_2d[0,:]
#arr_slice1

arr_slice2 = arr_2d[1,:]
#arr_slice2

arr_slice3 = arr_2d[2,:]
#arr_slice3

arr_slice3 = arr_2d[2,:]
#arr_slice3

arr_slice4 = arr_2d[3,:]
#arr_slice4

#arr_slice4 

new_order = [0,3,1,2]


arr_2d [new_order]










array([['1', '2', '3'],
       ['---', '---', '---'],
       ['4', '-1', '-1'],
       ['7', '8', '9']], dtype='<U21')

In [29]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])
scores

names == 'Bob'
scores[names == 'Bob',1]


array([80, 77])

In [30]:
scores[~(names=='Joe')]


array([[ 75,  80],
       [ 95, 100],
       [100,  77],
       [ 85,  92]])

In [31]:
names=='Joe'


array([False,  True, False, False, False,  True,  True])

In [32]:

mask = (names == 'Bob')| (names == 'Joe')
mask
scores[mask]
scores[scores<80]

array([75, 77, 72])

In [33]:
narr = np.zeros((8,4))
narr
for i in range(8):
    narr[i] = i
narr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [39]:
#new_order = [4,3,0,6]
narr[[4,3,0,6]]
narr[[-3,-5,-7  ]]



array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [40]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
arr.transpose()
arr.T
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])