In [1]:
print(1)


1


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr = arr * 2
arr


array([ 2,  4,  6,  8, 10])

In [7]:
arr = np.ones((5,5))
arr


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.average(arr)
arr.mean()

1.0

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr [1]

array([4, 5, 6])

In [18]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
type(my_arr)
type(my_list)
#my_arr
#my_list

list

In [22]:
arr = np.zeros((3,6))
arr.shape


(3, 6)

In [ ]:
arr = np.arange(15).reshape(5, 3)
arr
#arr[:2,:]
arr[:,:1]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [45]:
arr[:,:1]

array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12]])

In [46]:
arr[1,2]

5

In [48]:
arr[1,2] = 12
arr

array([[ 0,  1,  2],
       [ 3,  4, 12],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
a1 = np.arange(0,5)
a2 = np.arange(5,10)
np.union1d(a1,a2)
np.dot(a1,a2)


80