# Assignment

## Brief

Write the Python codes for the following questions.

## Instructions

Paste the answer as Python in the answer code section below each question.

### Question 1

Given the following numpy array:
```python
arr = np.array([1, 2, 3, 4, 5])
```
Write a Python code to multiply each element in the array by 2.

Answer:

In [7]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr = arr * 2
arr


array([ 2,  4,  6,  8, 10])

### Question 2

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to select the second row of the array.

Answer:

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr [1]



array([4, 5, 6])

### Question 3

Create a 2D numpy array of shape (5, 5) filled with the number 1.

Answer:

In [9]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Question 4

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to calculate the sum of all the elements in each row.

Answer:

In [10]:
arr.sum(axis=1)

array([5., 5., 5., 5., 5.])

### Question 5

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to calculate the average of all the elements.

Answer:

In [11]:
arr.mean()

1.0